---

- name: eda windows service management
  hosts: "{{ ansible_eda.event.payload.ProblemDetails.rankedEvents[0].customProperties.hostname }}"
  gather_facts: false
  connection: winrm
  vars:
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: basic
  tasks:
  - name: create servicenow incident
    servicenow.itsm.incident:
      short_description: "{{ ansible_eda.event.payload.ProblemID }} - {{ ansible_eda.event.payload.ProblemDetails.rankedEvents[0].customProperties.hostname }} - {{ ansible_eda.event.payload.ProblemDetails.rankedEvents[0].customProperties.OS_service_name }} is {{ ansible_eda.event.payload.ProblemDetails.rankedEvents[0].customProperties.Status }}"
      description: "{{ ansible_eda.event.payload.ProblemTitle }}"
      other:
        cmdb_ci: "{{ ansible_eda.event.payload.ProblemDetails.rankedEvents[0].customProperties.hostname }}"
    delegate_to: localhost
    register: sn_incident

  - name: print servicenow incident number
    ansible.builtin.debug:
      msg: "ServiceNow Incident Number - {{ sn_incident.record.number }}"

  - name: restart windows service
    ansible.windows.win_service:
      name: "{{ ansible_eda.event.payload.ProblemDetails.rankedEvents[0].customProperties.OS_service_name }}"
      state: started

  - name: close servicenow incident
    servicenow.itsm.incident:
      state: closed
      number: "{{ sn_incident.record.number }}"
      close_code: "Solved (Permanently)"
      close_notes: "Closed"
    delegate_to: localhost
